# DVC Pipeline Configuration
# This file defines the complete ML pipeline with dependencies and outputs

stages:
  preprocessing:
    cmd: python -m proyecto_final.scripts.run_preprocessing
    deps:
      - ../data/raw/energy_efficiency_modified.csv
      - preprocessing/transformers.py
      - preprocessing/pipeline.py
      - data/preprocessing.py
    outs:
      - ../data/interim/energy_efficiency_interim_clean.csv
      - ../data/processed/energy_efficiency_train_prepared.csv
      - ../data/processed/energy_efficiency_test_prepared.csv
      - ../models/initial_cleaning_pipeline.joblib
      - ../models/encoding_scaling_transformer.joblib

  train_xgboost:
#    cmd: python -m proyecto_final.train --config configs/xgb.yaml --skip-preprocessing
    cmd: HOME=$(pwd)/.. python -m proyecto_final.train --config configs/xgb.yaml --skip-preprocessing
    deps:
      - ../data/processed/energy_efficiency_train_prepared.csv
      - ../data/processed/energy_efficiency_test_prepared.csv
      - configs/xgb.yaml
      - modeling/trainer.py
    params:
      - configs/xgb.yaml:
          - model
          - split
          - hpo
    metrics:
      - ../models/xgboost_metrics.json:
          cache: false
    outs:
      - ../models/xgboost_heating_model.joblib
      - ../models/xgboost_cooling_model.joblib

  train_random_forest:
#    cmd: python -m proyecto_final.train --config configs/rf.yaml --skip-preprocessing
    cmd: HOME=$(pwd)/.. python -m proyecto_final.train --config configs/rf.yaml --skip-preprocessing
    deps:
      - ../data/processed/energy_efficiency_train_prepared.csv
      - ../data/processed/energy_efficiency_test_prepared.csv
      - configs/rf.yaml
      - modeling/trainer.py
    params:
      - configs/rf.yaml:
          - model
          - split
          - hpo
    metrics:
      - ../models/random_forest_metrics.json:
          cache: false
    outs:
      - ../models/random_forest_heating_model.joblib
      - ../models/random_forest_cooling_model.joblib
